export enum ROLES {
	ADMIN = 'ADMIN',
}

export enum STATUS {
	CANDIDATE_REJECTED = 'CANDIDATE_REJECTED',
	OFFER_ACCEPTED = 'OFFER_ACCEPTED',
	INTERVIEW_DONE = 'INTERVIEW_DONE',
	APPLIED = 'APPLIED',
	CONTACTED = 'CONTACTED',
	HIRED = 'HIRED',
	OFFER_MADE = 'OFFER_MADE',
	INTERVIEW_SCHEDULED = 'INTERVIEW_SCHEDULED',
}
